### ISSUE TITLE
Can't build with bitcode

### ISSUE THREAD

**Issue by Ruthberg** [Azure/azure-storage-ios#24]
I'm trying to use this with a much larger project, but linker complains that I have to compile with bitcode, as the larger project uses bitcode. Even when I change the build settings to compile using bitcode, it still doesn't work. Anyone else have this problem? Due to the size of the project I simply cannot submit without bitcode.

**Comment by asorrin-msft** [comment]
@Ruthberg - 
This is something we're looking at fixing with the 0.2 release, coming out very soon.  If you're set up to build the framework from source anyway, could you try building out of the dev branch of my personal fork:
https://github.com/asorrin-msft/azure-storage-ios/tree/dev
and see if that fixes the linker issue?

Thanks!

**Comment by Ruthberg** [comment]
Thank you @asorrin-msft. I tried this, but got an error when trying to use the framework.
<img width="335" alt="skjermbilde 2016-04-05 kl 09 05 31" src="https://cloud.githubusercontent.com/assets/12203923/14273858/f3744d82-fb0d-11e5-861e-1547a3e58596.png">

Could this be caused by these warnings when building the framework?
<img width="255" alt="skjermbilde 2016-04-05 kl 09 06 45" src="https://cloud.githubusercontent.com/assets/12203923/14273874/124ffb7a-fb0e-11e5-9d81-830daa5ddca8.png">

**Comment by asorrin-msft** [comment]
Sorry, the error is because I messed up the pbxproj file when adding some new features, and we haven't tested the framework for the 0.2 release yet.  Should be fixed now, in that same branch.  (And the warnings will be fixed before we actually ship :) )
Thanks again!

**Comment by Ruthberg** [comment]
@asorrin-msft thank you, this works brilliantly. When will the 0.2 version get released? I'll use this version  until then, but will have to replace it with the official once it ships.

**Comment by Ruthberg** [comment]
Pretty please, with sugar on top: Drop the asl.h library. It's a real pain in the <insert suitable anatomy here>
