### ISSUE TITLE
"AZSClient/AZSClient.h" file not found

### ISSUE THREAD

**Issue by lauthu** [Azure/azure-storage-ios#28]
got this error message after update. I followed steps in readme, and added
 `#import "AZSClient/AZSClient.h"`
 to my bridging header. Also tried
 `#import <AZSClient/AZSClient.h>`

**Comment by tiagotocha** [comment]
Hi lauthu! I Had the same problem. 

Try this:

Project -> Build Settings -> Search Paths -> Framework Search Paths
And add the .framework dirs. If you checked the option "Copy items if needed" like this screenshot
![image](https://cloud.githubusercontent.com/assets/3675530/15427881/7961efde-1e6e-11e6-9f1c-6ffe7c886a43.png)
Just add  $(PROJECT_DIR) in the values.

**Comment by zezha-msft** [comment]
@tiagotocha Thanks for helping out! 👍
