### ISSUE TITLE
CocoaPods package

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-storage-ios#3]
Any plans to publish on cocoapods?

**Comment by asorrin-msft** [comment]
Absolutely!  We need a bit of time to work out our complete ship story, but we definitely plan on publishing to CocoaPods.

**Comment by esummers-msft** [comment]
We released a CocoaPod!  You can find it at https://cocoapods.org/?q=AZS
Please let us know if there is anything else you would like to see, related to this library.

**Comment by ahmetalpbalkan** [comment]
awesome! thanks.
