### ISSUE TITLE
Azure Storage breaks when I call AZSCloudBlob in Swift

### ISSUE THREAD

**Issue by akawther** [Azure/azure-storage-ios#35]
I've followed this article: Azure Storage Client Library for iOS and their sample works. But now I am trying to bring the azure-related code to my own project. I added the framework per instructions and show up like this in my project:
![screen shot 2016-06-01 at 2 52 20 am](https://cloud.githubusercontent.com/assets/19243991/15702961/811112c6-27a8-11e6-8baa-fb37922533f7.png)

But when I uncomment the 3rd line and try to build:
`var containerURL: String = ""
let usingSAS = true
var blobs = [AZSCloudBlob]() // uncommenting this results into build error
//var container : AZSCloudBlobContainer = AZSCloudBlobContainer()
//var continuationToken : AZSContinuationToken?`

I get this build error: 

![screen shot 2016-06-01 at 2 27 06 am](https://cloud.githubusercontent.com/assets/19243991/15703020/ccc79cda-27a8-11e6-8e9f-7a07cb0375fa.png)

I've modeled my setting like this: 
![screen shot 2016-06-01 at 2 26 25 am](https://cloud.githubusercontent.com/assets/19243991/15703047/e91143be-27a8-11e6-95d0-4ddf7fadf19d.png)

**Comment by asorrin-msft** [comment]
Sorry this took me forever to get back to you, I wasn't able to repro your issue or figure out what might have gone wrong, but I finally came up with something.  What's your setting for "Allow Non-modular Includes In Framework Modules"?  I believe this needs to be set to "Yes" to use the Storage library.  This should be in our docs, I'll check... if it's not, I'll make sure to update them.

**Comment by zezha-msft** [comment]
Closing due to lack of reply. Please feel free to reopen.
