### ISSUE TITLE
+[AZSCloudStorageAccount accountFromConnectionString:error:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by vtcajones** [Azure/azure-storage-ios#37]
I just updated to whatever the latest version is via cocoapods and I'm getting this error when trying to instantiate an AZSCloudStorageAccount object via swift:

ex: 
`let account = try! AZSCloudStorageAccount(fromConnectionString: "DefaultEndpointsProtocol=https;AccountName=\(accountName!);AccountKey=\(accountKey!)")`

this worked fine before the update minus the `try!` since the call now throws.

**Comment by kfarmer-msft** [comment]
Thank you for your message.  We are looking into it and will get back to you.

**Comment by vtcajones** [comment]
I'm still seeing this, however I'm only noticing this on one of my machines. If I build the project on a different machine it works fine, but not my primary one.

**Comment by vtcajones** [comment]
Deleting the project contents in the DerivedData folder fixed this, for anyone else that might be running into this.

**Comment by zezha-msft** [comment]
@vtcajones Thank you so much for figuring this out! 👍
