### ISSUE TITLE
0.2.2 pod creates freeze on build while compiling source files 

### ISSUE THREAD

**Issue by gmxu** [Azure/azure-storage-ios#38]
Whenever I include the 0.2.2 pod and build my project, my project freezes on the compiling source files. This doesn't happen if I compile azure-storage-ios myself and including it as a framework or if I'm using the 0.1.2 pod.

**Comment by kfarmer-msft** [comment]
Thanks for raising this.  Could you let us know and the xcode version you're developing with, and the framework version you are targeting?

**Comment by zezha-msft** [comment]
Closing due to lack of reply. Please feel free to reopen.
