### ISSUE TITLE
How to [AZSCloudBlockBlob initWithUrl]

### ISSUE THREAD

**Issue by nor0x** [Azure/azure-storage-ios#40]
How can i initialize an `AZSCloudBlockBlob ` with a url (which i get from an API that returns SASurls). In the `AZSBlobSasTests.m` file `AZSUriQueryBuilder` is used to create the url for the initialization. But i can't import `AZSUriQueryBuilder .h`in my file.

[https://github.com/Azure/azure-storage-ios/blob/5ddb81d20e9acb7bd8db8ed7f55a6b96d6f78cdc/Lib/Azure%20Storage%20Client%20Library/Azure%20Storage%20Client%20LibraryTests/AZSBlobSasTests.m](url)

I tried to split the url from my API to the format which works on the Windows client, but with no success. Any help is appreciated.
Thank you

**Comment by asorrin-msft** [comment]
AZSUriQueryBuilder.h is for internal use only, you shouldn't have to pay any attention to it (and we should rip it out of the unit tests if possible, I'll look into that.)  For using a URL, you should be able to do something like (just typing this out from memory, but it should be close):

NSString *urlString = @"https://account.blob.core.windows.net/container/blob?fullSAStoken";
NSURL *url = [[NSURL alloc] initWithString:urlString];

NSError *error = nil;
AZSCloudBlockBlob *sasBlob = [[AZSCloudBlockBlob alloc] initWithUrl:url error:&error];

Is this not working?  What kind of failure are you seeing?  And can you give a sample of the URL you're using (with sensitive parts removed)?

Thanks

**Comment by nor0x** [comment]
It was an encoding issue with the url i received from the API. Everything is working now with the correct format.

Closed
