### ISSUE TITLE
Failed to compile from source

### ISSUE THREAD

**Issue by epot** [Azure/azure-storage-ios#45]
I am trying to follow the steps from the README:

- clone the master branch
- open the xcode project
- compile the AZSClient library
- compile the framework target: at this poing I get a strange "xcrun: error: Unknown build action 'xcodebuild'."

I am using the latest XCode 8.1 on MacOS Sierra.

**Comment by micurd** [comment]
Hi @epot. We haven't been able to repro this error, yet. We've tested this on XCode 8.1 with MacOS Sierra version 10.12.1. Would there happen to be any other text provided by the error? To clarify, all the steps you've provided were completed through Xcode and not the command-line, correct?

**Comment by epot** [comment]
Hey ! Thanks for the reply. Yes, I am doing that from XCode directly:

- I open Xcode
- Select iPhone 5 simulator as device
- Build the current target (which is the Azure Storage Client Library)
- Change the target to Framework and build
It fails with the following output:

> CONFIGURATION = Debug
Build settings from command line:
    ARCHS = i386 x86_64
    BUILD_DIR = /Users/epot/Library/Developer/Xcode/DerivedData/AZSClient-clwhusieqymcyyeogbqlwgncnxxq/Build/Products
    BUILD_ROOT = /Users/epot/Library/Developer/Xcode/DerivedData/AZSClient-clwhusieqymcyyeogbqlwgncnxxq/Build/Products
    OBJROOT = /Users/epot/Library/Developer/Xcode/DerivedData/AZSClient-clwhusieqymcyyeogbqlwgncnxxq/Build/Intermediates
    ONLY_ACTIVE_ARCH = NO
    OTHER_CFLAGS = -fembed-bitcode
    SDKROOT = iphonesimulator10.1
    SYMROOT = /Users/epot/Library/Developer/Xcode/DerivedData/AZSClient-clwhusieqymcyyeogbqlwgncnxxq/Build/Products
    TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault

xcrun: error: Unknown build action 'xcodebuild'.
Command /bin/sh failed with exit code 65

**Comment by micurd** [comment]
Hmm, we're still not able to repro and have also set iPhone 5 as the simulator device. Does this issue occur when building other libraries from source?

**Comment by epot** [comment]
No, this is the only case unfortunately :-(.
