### ISSUE TITLE
Need file support!

### ISSUE THREAD

**Issue by gerchicov-bp** [Azure/azure-storage-ios#46]
Or maybe could you explain if it is possible to work with files+folders via blobs?

**Comment by jofriedm-msft** [comment]
Hi @gerchicov-bp . you can include delimiters (such as '/') within a blob name to create a hierarchy. ie if a folder is named 'a' then all blobs in that folder could prefixed with "a/". More information on naming can be found [here](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/naming-and-referencing-containers--blobs--and-metadata) and more general information about [blobs](https://docs.microsoft.com/en-us/azure/storage/storage-ios-how-to-use-blob-storage)

**Comment by mirobers** [comment]
@gerchicov-bp does this answer your question? If not, feel free to reopen this issue with more details.
