### ISSUE TITLE
Unspecified error when initializing storage account in sample app

### ISSUE THREAD

**Issue by krambs** [Azure/azure-storage-ios#47]
Xcode 8.2.1

When running sample app (and before, when running my own app via Cocoapods) I get this error when initializing AZSCloudStorageAccount: `Error Domain=com.Microsoft.AzureStorage.ErrorDomain Code=1 "(null)"`

from the line `try! storageAccount = AZSCloudStorageAccount(fromConnectionString: connectionString)` in BlobListTableViewController.swift

Any advice on how to debug to nail down the error further would be great!

**Comment by zezha-msft** [comment]
Hi Krambs, thanks for your feedback!

Error domain Code=1 means invalid argument, could you please double check that you put in the right AccountName and AccountKey? We will document these errors properly in the near future, sorry for the confusion!

A simple way to verify your credentials is to use the [Azure Storage Explorer](http://storageexplorer.com/), it also allows you to visualize your storage account.

Please do reopen this issue if you're still encountering the same problem.

**Comment by raudabaugh** [comment]
I was getting the same error using a Connection String generated by Azure Storage Explorer. Deleting the `/;` from the end of the string solved it for me.
