### ISSUE TITLE
Receiving a lot of crashes on this line with many of our users. Has anyone else come across this issue ?

### ISSUE THREAD

**Issue by zsteed** [Azure/azure-storage-ios#49]
Crashed: Thread
2  AZSClient 
AZSBlobUploadHelper write:maxLength:completionHandler:
Line: 186

**Comment by kfarmer-msft** [comment]
Thank you.  I've raised this to those working on the iOS library.

**Comment by zezha-msft** [comment]
Thank you for the feedback. We will look into this problem and update this thread accordingly.

**Comment by zezha-msft** [comment]
@zsteed Thank you for your patience. I am looking into this issue right now. Are you still encountering the crash? If yes, could you please provide me with a bit more context? For example, which kind of blob are you uploading, and whether there's any pattern in the crashes, does it only happen when the blob size is large? And is there any other error message on the crash?

**Comment by zsteed** [comment]
Sorry, I removed this library from my app a long time ago and started using the Azure REST API. Good luck.

**Comment by zezha-msft** [comment]
@zsteed I'm really sorry to hear that. I apologize for the inconveniences, we are committed to make this library better.

I'll close this issue for now, and reopen it if anybody else encounters this problem.
