### ISSUE TITLE
Naming convention and import path

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-storage-ios#5]
#import "Azure Storage Client Library/Azure_Storage_Client_Library.h"

is this actually idiomatic in Objective-C/Cocoa SDK? 

I've never seen:

* directory names with spaces
* header files with underscores

also class names in this library starts with AZ, but the import statement does not have AZ in it.

Take a look at these examples:

```objc
#import <UIKit/UIKit.h>
...
UINavigationController* n = ...
```

```objc
#import "AFNetworking/AFNetworking.h>
...
AFHTTPRequestSerializer* s = ...
```

So I think this library should be something like:

    #import "AZStorage/AZStorage.h"

because:

* `_Client` = obvious
* `_Library` = obvious

**Comment by asorrin-msft** [comment]
Sorry for the delay in response.  Excellent point.  We're not going to be able to make the change for the next release (0.1.1, minor bugfixes), but 0.2 will fix this (which we're working on features for now).  We might do something like "AZSClient/AZSClient.h", though, because the prefix we use is actually "AZS".  Would this be more idiomatic?

**Comment by ahmetalpbalkan** [comment]
I think so.

**Comment by ahmetalpbalkan** [comment]
However I really suggest dropping `Client` as well and calling it AZStorage. In the future if we develop resource provider APIs, we'd probably do something like `#import <AZCompute/AZCompute.h>`. I suggest looking at how others have been doing so far for this naming convention. I think it's important to get it right.

Cocoa SDK and ecosystem libraries tend to have these single `.h` files where all exported symbols (types, constants etc) in that framework are referenced (by importing other .h files). So developers can actually just import a single header file and use the whole package. 

cc: @devigned
