### ISSUE TITLE
com.Microsoft.AzureStorage.ErrorDomain error 3

### ISSUE THREAD

**Issue by Ruthberg** [Azure/azure-storage-ios#50]
I get this error quite often: 
The operation couldn’t be completed. (com.Microsoft.AzureStorage.ErrorDomain error 3.)

I'm using blobstorage with SAS, and the only thing I can do once I get this error seems to be to get a new SASURI and try again. Why does this happen, and is there anything I can do to avoid these?

Adding some code here for context:

`
let url = URL(string: doc.resourceUri!)
        let storageUri = AZSStorageUri(primaryUri: url!)
        var error:NSError?
        let blob = AZSCloudBlockBlob(storageUri: storageUri, error: &error)
       
        blob.upload(from: data, completionHandler: { (error:Error?) -> Void in
            if error != nil && error?.localizedDescription != nil
            {
                let failureDescription = error?.localizedDescription
                doc.uploadStatus = UploadStatus.default.rawValue as NSNumber?
                doc.resourceUri = nil
                appdelegate.saveContext()
                self.blobCheckInProgress = false
                return
            }
            else
            {
                doc.uploadStatus = UploadStatus.uploaded.rawValue as NSNumber?
                doc.expense?.syncronized = NSNumber(value : false)
                doc.travelExpenseEntry?.syncronized = NSNumber(value : false)
                doc.travelExpenseEntry?.travelExpense?.syncronized = NSNumber(value : false)
                
                if StaticOperations.stringIsNilOrEmpty(input: doc.temporaryId)
                {
                    doc.temporaryId = UUID().uuidString
                }
            }
            
            appdelegate.saveContext()
            self.blobCheckInProgress = false
            self.checkForBlobsToUpload()
        })`

**Comment by zezha-msft** [comment]
Hi Ruthberg, thank you for the feedback!

Could you please double check whether the SAS was still valid when your request fails? There is an expiration time on the blob SAS. In addition, could you please also verify that the SAS has the correct (write) permissions?

If you still encounter this problem, please let us know and we will look into it ASAP! Thank you.

**Comment by Ruthberg** [comment]
Hi Zezha, thank you for the quick response. Unfortunately it is near impossible to know if the the upload happened within the SAS time limit, as this happens on the phones of our customers. The intended use case is that once an image is ready for upload, the app makes a service call to get a SAS URI, and then immediately upload the file. The SAS URI will always have RW access for 30 minutes, which should be ample for the task. It is however conceivable that the network access is enough to successfully get the SAS URI, but not good enough for the upload. This could possibly cause a retry outside the SAS time limit. But as you can see from the code above, any error will be dealt with by resetting the resourceUri (SAS URI) to nil, which will force the app to request a new SAS URI before any retries can be performed. Are there any logs available to us on the server side that could possibly help us figure this out?

**Comment by zezha-msft** [comment]
Hi Ruthberg, thank you for the additional details!

I was wondering how were you able to observed these failures? If it's not possible to know when did the failures happen (within or after the SAS time limit), do you know whether the upload eventually succeeds? And finally, were you able to reproduce this problem on your test devices? 

Please let me know, and we will assess how we should proceed to investigate this problem. Thank you!

**Comment by Ruthberg** [comment]
No we did not observe these failures. We just get screenshots from our customers with a popup alert saying "Action could not be completed" and the errorDomain message. Sometimes that code is 2, but it's usually 3. So far we could not reproduce this. We changed our strategy from uploading to our own services and then let our servers take care of storing the files to Azure, to using this library to allow the mobile devices to do this directly because this would greatly reduce load on our servers. Could there be any limitations in the azure storage services that could explain these failures? I realize that this is not an easy situation to assist in, and I greatly appreciate your help. We could enroll you as an external tester via Test Flight if you would like to test our app yourself, but I'm not very hopeful that you would be able to reproduce this error.

**Comment by zezha-msft** [comment]
Hi Ruthberg, thanks for providing more insights about your setup.

I'm afraid that we would need a lot more information about the failing requests in order to investigate them, such as the requestID and timestamp of the failure. Before looking into the service side, there are a few things that I would like to suggest, which could help in nailing down this problem:

- Detect, log, and post these errors and anything else included in the NSError to your servers (or another place) for later analysis, logging the SAS token used would be great too.
- Make sure the blob exists at the time of upload.
- Make sure the SAS is not expired at the time of upload.

I was wondering, is it possible that your customers pressed the home button or switched application while the upload is going on? I think that it's very unlikely that this problem was caused by limitations in Azure Storage ([SLA](https://azure.microsoft.com/en-us/support/legal/sla/storage/v1_2/)).

Please let me know if you have any other question! Thank you!

**Comment by Ruthberg** [comment]
Hi Zezha, thank you for the advice. I will make sure to implement detailed logging, then maybe we will get some better answers. I will get back to you if I need any more assistance.

**Comment by zezha-msft** [comment]
Thank you @Ruthberg! Please reopen this issue once you have more information. 👍

**Comment by zezha-msft** [comment]
@Ruthberg Maybe [this](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/storage-analytics) could help you too!
