### ISSUE TITLE
Issue with AZSNullable types when called from swift code

### ISSUE THREAD

**Issue by gerardomedina** [Azure/azure-storage-ios#62]
Hi, I'm using the this library from cocoapods but I detected an issue with the method 
-(void)uploadFromData:(NSData *)sourceData completionHandler:(void (^)(NSError* AZSNullable))completionHandler; 
and probably other methods, when calling them from swift code, in my case I'm calling this method like this:

       :
       :
       blob.upload(from: data, completionHandler: {(error) in
            if error != nil {
                    //print the error
            } else {
    	            //success
            }
      })

And the issue is that the property "error" in the closure doesn't have the correct type because the app crashes (on real devices) and also I get this warning "Comparing non-optional value of type 'Error' to nil always returns true" in this line:
if error != nil {
:

it's saying that the error cannot be nil but it is nil when the upload is success, and that's correct because the description of the method says the following: "NSError* will be Nil if the operation succeeded without error, error with details about the failure otherwise", as you can see in the declaration (found in AZSCloudBlockBlob.h)

 | Parameter name | Description |
 |----------------|-------------|
 |NSError * | Nil if the operation succeeded without error, error with details about the failure otherwise.|

-(void)uploadFromData:(NSData *)sourceData completionHandler:(void (^)(NSError * AZSNullable))completionHandler;

I can avoid this error by changing the type from (NSError* AZSNullable) to (NSError* __AZSNullable), but even after that xcode is showing some warnings in the implementation of this method from swift code.

Can you please review these methods to ensure they work correctly when called from Swift?

Thanks in advance

**Comment by zezha-msft** [comment]
@gerardomedina I really apologize for the late response. I'll make a fix as soon as possible. Thank you for bringing this to us.

**Comment by gerardomedina** [comment]
thank you @zezha-msft

**Comment by zezha-msft** [comment]
Fixed with [release](https://github.com/Azure/azure-storage-ios/releases/tag/v0.2.5).
