### ISSUE TITLE
x-ms-blob-type

### ISSUE THREAD

**Issue by janhalousek** [Azure/azure-storage-ios#64]
I am creating `AZSCloudBlockBlob` with SAS URL I obtain from our backend. Then I try to upload data, seeing response of HTTP 403 with message: `Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature...`
```
var error: NSError?
let blockBlob = AZSCloudBlockBlob(url: mySASURL, error: &error)
blockBlob.upload(from: data) { (error) in
  // http 403
}
```
Solution: I inspected the request this framework creates and discovered that header with key `x-ms-blob-type` is missing. And according to [ms docs](https://docs.microsoft.com/en-us/rest/api/storageservices/Put-Blob?redirectedfrom=MSDN) is required. Using [Postman](https://www.getpostman.com), I created this PUT request including `x-ms-blob-type` and it works.

**Comment by janhalousek** [comment]
I don't understand it, but I came back to the code today and it worked (http 201). I changed nothing, I just wanted to check the http headers generated by this framework again. Seems unstable though, should I close this issue?

**Comment by zezha-msft** [comment]
Hi @janhalousek, sorry for the late reply!

I'll close this for now, but please let me know if you see the issue again. Thanks!
