### ISSUE TITLE
[Swift] Missing Nullability in AZSCloudBlockBlob upload:from:completionHandler:

### ISSUE THREAD

**Issue by husnusener** [Azure/azure-storage-ios#66]
Hi,

I've installed AZSClient throught CocoaPods. I'm using swift in my development and I want to upload a blob with contents from Data object; however, in completionHandler, type of error is Error, not Error?, therefore swift warns me that it can never be null. With a non-nullable error, I cannot check whether upload is successful or not, even worse, app may crash when Obj-C code tries to return nil. I haven't runned it, but it is likely to cause problem. 

Other upload methods does not have this problem, I can use upload:from:accessCondition:requestOptions:operationContext:completionHandler by giving null to all other parameters for now. But I hope you'll fix this bug as soon as possible.

Have a nice day!

**Comment by zezha-msft** [comment]
@husnusener I really apologize for the late response. I'll make a fix as soon as possible. Thank you for bringing this to us.

**Comment by zezha-msft** [comment]
Fixed with [release](https://github.com/Azure/azure-storage-ios/releases/tag/v0.2.5).
