### ISSUE TITLE
Apps crashes every now and then due to this line of code. Am i the only one experiencing this?

### ISSUE THREAD

**Issue by IfyNdu** [Azure/azure-storage-ios#67]
Hi, I receive irregular crashes whilst downloading blobs from the storage and here is the error i get --> [https://puu.sh/y7DPX/04d3f2057b.png](url)

Maybe its me or i'm doing something wrong

**Comment by IfyNdu** [comment]
much more detailed image
<img width="950" alt="screen shot 2017-10-26 at 21 19 13" src="https://user-images.githubusercontent.com/15639127/32075060-7bd99614-ba93-11e7-9159-f780e0e3d70f.png">

**Comment by Emifus** [comment]
I am experiencing this as well.

**Comment by IfyNdu** [comment]
Strange! I’ve scoured the Internet for an interim workaround but no one seems to have experienced this behaviour so far.

**Comment by zezha-msft** [comment]
Hi @IfyNdu, do you only see this issue on a device? Does it happen with simulators too? On which devices have you seen it so far? Thanks!

**Comment by IfyNdu** [comment]
Hi, both on an actual device and simulator. Basically on all devices.

**Comment by Emifus** [comment]
I am experiencing it consistently across all iOS 11.x devices and sims I've run it on, but have not had a chance to test on iOS 10.

**Comment by IfyNdu** [comment]
It’s crashes on me on iOS10 and 11. I really can’t remember if this was the case in iOS 9 however it’s been crashing on me since I started using it.

**Comment by zezha-msft** [comment]
This issue seems quite strange, I'll try to repro it. Thanks!

**Comment by husnusener** [comment]
I also have this issue. I guess the problem is that NSDateFormatter is not thread-safe; however a static singleton instance is used among various calls. Therefore when you initiate multiple requests (Upload in my case), randomly a race condition arises and this crash appears.

Currently I'm queueing requests and wait each ones completion to initiate the next for avoiding this error.

Here is my screenshot, I've taken it a lot time ago but forgot to post here due other stuff. If you fix this issue urgently, it would help me a lot. 

<img width="1021" alt="azurecrash" src="https://user-images.githubusercontent.com/12456572/33515107-bab212d2-d76f-11e7-820f-a993d03bef3f.png">

**Comment by mannie** [comment]
The problem is indeed thread-safety, well, lack thereof. I presume `df` is being used as a common base date formatter from which others are derived. 

The recommended way of creating singletons on iOS is through the use of `dispatch_once`. Consider trying the following snippet:

```
+ (NSDateFormatter *)dateFormatterWithFormat:(NSString *)format {
    static NSDateFormatter *df;
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        df = [[NSDateFormatter alloc] init];
        [df setLocale:[[NSLocale alloc] initWithLocaleIdentifier:AZSCPosix]];
        [df setCalendar: [[NSCalendar alloc] initWithCalendarIdentifier:AZSGregorianCalendar]];
        [df setTimeZone:[NSTimeZone timeZoneWithName:AZSCUtc]];
    });
    
    NSDateFormatter *dateFormat = [df copy];
    [dateFormat setDateFormat:format];
    return dateFormat;
}
```

**Comment by IfyNdu** [comment]
@mannie @husnusener Thanks for your insight and interim work arounds. I'll apply @mannie solution and let you know how it gets on.

**Comment by jayMcBee** [comment]
Thanks @mannie - that is my local solution as well as apps using Azure SDKs on iOS and macOS crash a lot in this method for our users.

Makes me wonder whether they're actually used internally by MS as they're virtually unusable in their current state due to this threading bug?!

**Comment by zezha-msft** [comment]
Hi @mannie, thank you so much for the insights. Would you like to submit a PR?

**Comment by mannie** [comment]
@zezha-msft https://github.com/Azure/azure-storage-ios/pull/77

**Comment by LoganKlein** [comment]
Any progress on this issue? I'm still experiencing frequent crashes.

**Comment by zezha-msft** [comment]
Hi @LoganKlein, are you using the latest version? It should have been fixed. Thanks.
