### ISSUE TITLE
DateFormatterWithFormat is not thread safe

### ISSUE THREAD

**Issue by aramark-pivotal** [Azure/azure-storage-ios#74]
When attempting to retrieve blob attributes we encounter an occasional application crash pointing to `[df setLocale:[[NSLocale alloc] initWithLocaleIdentifier:AZSCPosix]];` can this be synchronized?

`+(NSDateFormatter *) dateFormatterWithFormat:(NSString *)format
{
    static NSDateFormatter *df = nil;
    if (!df) {
        df = [[NSDateFormatter alloc] init];
        [df setLocale:[[NSLocale alloc] initWithLocaleIdentifier:AZSCPosix]];
        [df setCalendar: [[NSCalendar alloc] initWithCalendarIdentifier:AZSGregorianCalendar]];
        [df setTimeZone:[NSTimeZone timeZoneWithName:AZSCUtc]];
    }
    
    NSDateFormatter *dateFormat = [df copy];
    [dateFormat setDateFormat:format];
    return dateFormat;
}`

**Comment by mannie** [comment]
Might I propose referring to this thread for a solution, please: https://github.com/Azure/azure-storage-ios/issues/67#issuecomment-358861466

**Comment by jayMcBee** [comment]
Same here - crashes the app in 

+ [AZSUtil dateFormatterWithFormat:] 

so azure-storage-ios is effectively not usable on all Apple platforms as of today!

**Comment by zezha-msft** [comment]
Duplicate of #67
