### ISSUE TITLE
Blob upload fails with 400 error code and the Message warning

### ISSUE THREAD

**Issue by mhty19891833** [Azure/azure-storage-ios#85]
task.error:Error Domain=com.Microsoft.AzureStorage.ErrorDomain Code=3 "(null)" UserInfo={Code=InvalidHeaderValue, AdditionalErrorDetails={
    HeaderName = "Content-MD5";
    HeaderValue = "SAVEFILE/20180710/7ed8de1db07b40dba99b2bd66ff60cc2.png";
}, rawErrorData=<CFData 0x1353c2840 [0x1b433a538]>{length = 371, capacity = 371, bytes = 0xefbbbf3c3f786d6c2076657273696f6e ... 3c2f4572726f723e}, OperationContext=<AZSOperationContext: 0x1352ca470>, RequestResult=<AZSRequestResult: 0x1353c7190>, HTTP Status Code=400, URLResponse=<NSHTTPURLResponse: 0x1353c6ea0> { URL: https://exce.blob.core.chinacloudapi.cn/o-test/exce?comp=block&blockid=exce } { Status Code: 400, Headers {
    "Content-Length" =     (
        371
    );
    "Content-Type" =     (
        "application/xml"
    );
    Date =     (
        "Tue, 10 Jul 2018 09:09:56 GMT"
    );
    Server =     (
        "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0"
    );
    "x-ms-request-id" =     (
        "7488ed28-201e-0056-4e2d-1849c3000000"
    );
    "x-ms-version" =     (
        "2015-04-05"
    );
} }, Message=The value for one of the HTTP headers is not in the correct format.
RequestId:7488ed28-201e-0056-4e2d-1849c3000000
Time:2018-07-10T09:09:56.8943944Z}

**Comment by zezha-msft** [comment]
Hi @mhty19891833, thanks for reaching out.

It looks like your Content-MD5 is not valid. Please make sure to pass in a valid MD5 value, or not pass in anything.
