### ISSUE TITLE
SAS Token from a Shared Access Policy

### ISSUE THREAD

**Issue by ReveelTeam** [Azure/azure-storage-ios#89]
### Which version of the SDK/iOS was used?
latest (0.2.6)

### What problem was encountered?
how to generate a SAS-token from a blob-container's Access-Policy, from the iOS Client SDK?

Also is this SDK being worked on? -if so when will there be another release? 

### Have you found a mitigation/solution?
no.

**Comment by zezha-msft** [comment]
Hi @ReveelTeam, please refer to this [unit test](https://github.com/Azure/azure-storage-ios/blob/master/Lib/Azure%20Storage%20Client%20Library/Azure%20Storage%20Client%20LibraryTests/AZSBlobSasTests.m#L445) to see how to generate SAS using access policies.

Unfortunately this SDK is not being worked on at the moment. We are planning on providing a better solution but I do not have a timeline to share yet. Sorry about the inconvenience.
