### ISSUE TITLE
I'm receiving Failed to emit precompiled header for bridging header

### ISSUE THREAD

**Issue by MMooreGitHub** [Azure/azure-storage-ios#90]
### Which version of the SDK/iOS was used?
Xcode 10/ Swift 3

### What problem was encountered?
I'm receiving Failed to emit precompiled header for bridging header when building your BlobSample project after installing cocoa pods and running in the workspace

### Have you found a mitigation/solution?
No, that's why I'm opening this ticket.
I've tried the accepted answer under:
https://stackoverflow.com/questions/45779591/failed-to-emit-precompiled-header-for-bridging-header - still no luck

**Comment by prabh045** [comment]
i am also facing same issue. did you find sometjing?
