### ISSUE TITLE
Update required for Framework Instructions for Xcode 10

### ISSUE THREAD

**Issue by MMooreGitHub** [Azure/azure-storage-ios#92]
The following error was encountered when attempting to build the framework perf steps 3-4 under the Framework section of your instructions:

accessing build database "/Users/Library/Developer/Xcode/DerivedData/AZSClient-gfrzeddjhopquhfbkygxmchevldt/Build/Intermediates.noindex/XCBuildData/build.db": **database is locked Possibly there are two concurrent builds running in the same filesystem location**.

To resolve this, the following steps should be added between Steps 3 and 4 of the Manual Framework instructions for Xcode 10+ users (or the script should be fixed):
3. (pre-existing) At the top-left of Xcode, change the active scheme from "Azure Storage Client Library" to "Framework".
4. Select the framework Target => Mutiplatform Build 
5. Within the script change [OBJROOT="${OBJROOT}"] to: [OBJROOT="${OBJROOT}/DependentBuilds"]
6. (pre-existing) Build the project (⌘+B). This will create an AZSClient.framework file on your Desktop.

**Comment by egepointr** [comment]
Wow - you just saved me 2 hours of pain
Thank you!

**Comment by nickwph** [comment]
Try this: https://github.com/nickwph/AZSClient-Carthage

**Comment by MMooreGitHub** [comment]
Thank you. I'm no longer using Azure and did not test your solution. Hopefully, it will help another developer.
